module.exports = Object.freeze({
  AED: {
    id: 784,
    code: "AED",
    currency_name: "United Arab Emirates Dirham",
    region: "UNITED ARAB EMIRATES",
  },
  AFN: {
    id: 971,
    code: "AFN",
    currency_name: "Afghani",
    region: "AFGHANISTAN",
  },
  ALL: {
    id: 8,
    code: "ALL",
    currency_name: "Albanian Lek",
    region: "ALBANIA",
  },
  AMD: {
    id: 051,
    code: "AMD",
    currency_name: "Armenian Dram",
    region: "ARMENIA",
  },
  ANG: {
    id: 532,
    code: "ANG",
    currency_name: "Netherlands Antillean Guilder",
    region: "CURACAO",
  },
  AOA: {
    id: 973,
    code: "AOA",
    currency_name: "Angolan Kwanza",
    region: "ANGOLA",
  },
  ARS: {
    id: 032,
    code: "ARS",
    currency_name: "Argentine Peso",
    region: "ARGENTINA",
  },
  AUD: {
    id: 036,
    code: "AUD",
    currency_name: "Australian Dollar",
    region: "AUSTRALIA",
  },
  AWG: {
    id: 533,
    code: "AWG",
    currency_name: "Aruban Florin",
    region: "ARUBA",
  },
  AZN: {
    id: 944,
    code: "AZN",
    currency_name: "Azerbaijanian Manat",
    region: "AZERBAIJAN",
  },
  BAM: {
    id: 977,
    code: "BAM",
    currency_name: "Convertible Mark",
    region: "BOSNIA AND HERZEGOVINA",
  },
  BBD: {
    id: 052,
    code: "BBD",
    currency_name: "Barbados Dollar",
    region: "BARBADOS",
  },
  BDT: {
    id: 050,
    code: "BDT",
    currency_name: "Bangladeshi Taka",
    region: "BANGLADESH",
  },
  BGN: {
    id: 975,
    code: "BGN",
    currency_name: "Bulgarian Lev",
    region: "BULGARIA",
  },
  BHD: {
    id: 48,
    code: "BHD",
    currency_name: "Bahraini Dinar",
    region: "BAHRAIN",
  },
  BIF: {
    id: 108,
    code: "BIF",
    currency_name: "Burundi Franc",
    region: "BURUNDI",
  },
  BMD: {
    id: 060,
    code: "BMD",
    currency_name: "Bermudian Dollar",
    region: "BERMUDA",
  },
  BND: {
    id: 096,
    code: "BND",
    currency_name: "Brunei Dollar",
    region: "BRUNEI DARUSSALAM",
  },
  BOB: {
    id: 68,
    code: "BOB",
    currency_name: "Boliviano",
    region: "BOLIVIA",
  },
  BRL: {
    id: 986,
    code: "BRL",
    currency_name: "Brazilian Real",
    region: "BRAZIL",
  },
  BSD: {
    id: 044,
    code: "BSD",
    currency_name: "Bahamian Dollar",
    region: "BAHAMAS (THE)",
  },
  BTN: {
    id: 064,
    code: "BTN",
    currency_name: "Bhutanese Ngultrum",
    region: "BHUTAN",
  },
  BWP: {
    id: 072,
    code: "BWP",
    currency_name: "Botswanan Pula",
    region: "BOTSWANA",
  },
  BYR: {
    id: 974,
    code: "BYR",
    currency_name: "Belarussian Ruble",
    region: "BELARUS",
  },
  BZD: {
    id: 084,
    code: "BZD",
    currency_name: "Belize Dollar",
    region: "BELIZE",
  },
  CAD: {
    id: 124,
    code: "CAD",
    currency_name: "Canadian Dollar",
    region: "CANADA",
  },
  CDF: {
    id: 976,
    code: "CDF",
    currency_name: "Congolese Franc",
    region: "CONGO",
  },
  CHF: {
    id: 756,
    code: "CHF",
    currency_name: "Swiss Franc",
    region: "SWITZERLAND",
  },
  CLP: {
    id: 152,
    code: "CLP",
    currency_name: "Chilean Peso",
    region: "CHILE",
  },
  CNY: {
    id: 156,
    code: "CNY",
    currency_name: "Yuan Renminbi",
    region: "CHINA",
  },
  COP: {
    id: 170,
    code: "COP",
    currency_name: "Colombian Peso",
    region: "COLOMBIA",
  },
  CRC: {
    id: 188,
    code: "CRC",
    currency_name: "Costa Rican Colon",
    region: "COSTA RICA",
  },
  CUP: {
    id: 192,
    code: "CUP",
    currency_name: "Cuban Peso",
    region: "CUBA",
  },
  CVE: {
    id: 132,
    code: "CVE",
    currency_name: "Cabo Verde Escudo",
    region: "CABO VERDE",
  },
  CZK: {
    id: 203,
    code: "CZK",
    currency_name: "Czech Koruna",
    region: "CZECH REPUBLIC (THE)",
  },
  DJF: {
    id: 262,
    code: "DJF",
    currency_name: "Djibouti Franc",
    region: "DJIBOUTI",
  },
  DKK: {
    id: 208,
    code: "DKK",
    currency_name: "Danish Krone",
    region: "DENMARK",
  },
  DOP: {
    id: 214,
    code: "DOP",
    currency_name: "Dominican Peso",
    region: "DOMINICAN REPUBLIC (THE)",
  },
  DZD: {
    id: 012,
    code: "DZD",
    currency_name: "Algerian Dinar",
    region: "ALGERIA",
  },
  EGP: {
    id: 818,
    code: "EGP",
    currency_name: "Egyptian Pound",
    region: "EGYPT",
  },
  ERN: {
    id: 232,
    code: "ERN",
    currency_name: "Eritrean Nakfa",
    region: "ERITREA",
  },
  ETB: {
    id: 230,
    code: "ETB",
    currency_name: "Ethiopian Birr",
    region: "ETHIOPIA",
  },
  EUR: {
    id: 978,
    code: "EUR",
    currency_name: "Euro",
    region: "EUROPEAN UNION",
  },
  FJD: {
    id: 242,
    code: "FJD",
    currency_name: "Fiji Dollar",
    region: "FIJI",
  },
  FKP: {
    id: 238,
    code: "FKP",
    currency_name: "Falkland Islands Pound",
    region: "FALKLAND ISLANDS",
  },
  GBP: {
    id: 826,
    code: "GBP",
    currency_name: "Pound Sterling",
    region: "GUERNSEY",
  },
  GEL: {
    id: 981,
    code: "GEL",
    currency_name: "Georgian Lari",
    region: "GEORGIA",
  },
  GHS: {
    id: 936,
    code: "GHS",
    currency_name: "Ghana Cedi",
    region: "GHANA",
  },
  GIP: {
    id: 292,
    code: "GIP",
    currency_name: "Gibraltar Pound",
    region: "GIBRALTAR",
  },
  GMD: {
    id: 270,
    code: "GMD",
    currency_name: "Gambian Dalasi",
    region: "GAMBIA (THE)",
  },
  GNF: {
    id: 324,
    code: "GNF",
    currency_name: "Guinea Franc",
    region: "GUINEA",
  },
  GTQ: {
    id: 320,
    code: "GTQ",
    currency_name: "Guatemalan Quetzal",
    region: "GUATEMALA",
  },
  GYD: {
    id: 328,
    code: "GYD",
    currency_name: "Guyana Dollar",
    region: "GUYANA",
  },
  HKD: {
    id: 344,
    code: "HKD",
    currency_name: "Hong Kong Dollar",
    region: "HONG KONG",
  },
  HNL: {
    id: 340,
    code: "HNL",
    currency_name: "Honduran Lempira",
    region: "HONDURAS",
  },
  HRK: {
    id: 191,
    code: "HRK",
    currency_name: "Croatian Kuna",
    region: "CROATIA",
  },
  HTG: {
    id: 332,
    code: "HTG",
    currency_name: "Haitian Gourde",
    region: "HAITI",
  },
  HUF: {
    id: 348,
    code: "HUF",
    currency_name: "Hungarian Forint",
    region: "HUNGARY",
  },
  IDR: {
    id: 360,
    code: "IDR",
    currency_name: "Indonesian Rupiah",
    region: "INDONESIA",
  },
  ILS: {
    id: 376,
    code: "ILS",
    currency_name: "New Israeli Sheqel",
    region: "ISRAEL",
  },
  INR: {
    id: 356,
    code: "INR",
    currency_name: "Indian Rupee",
    region: "INDIA",
  },
  IQD: {
    id: 368,
    code: "IQD",
    currency_name: "Iraqi Dinar",
    region: "IRAQ",
  },
  IRR: {
    id: 364,
    code: "IRR",
    currency_name: "Iranian Rial",
    region: "IRAN (ISLAMIC REPUBLIC OF)",
  },
  ISK: {
    id: 352,
    code: "ISK",
    currency_name: "Iceland Krona",
    region: "ICELAND",
  },
  JMD: {
    id: 388,
    code: "JMD",
    currency_name: "Jamaican Dollar",
    region: "JAMAICA",
  },
  JOD: {
    id: 400,
    code: "JOD",
    currency_name: "Jordanian Dinar",
    region: "JORDAN",
  },
  JPY: {
    id: 392,
    code: "JPY",
    currency_name: "Japanese Yen",
    region: "JAPAN",
  },
  KES: {
    id: 404,
    code: "KES",
    currency_name: "Kenyan Shilling",
    region: "KENYA",
  },
  KGS: {
    id: 417,
    code: "KGS",
    currency_name: "Kyrgystani Som",
    region: "KYRGYZSTAN",
  },
  KHR: {
    id: 116,
    code: "KHR",
    currency_name: "Cambodian Riel",
    region: "CAMBODIA",
  },
  KMF: {
    id: 174,
    code: "KMF",
    currency_name: "Comoro Franc",
    region: "COMOROS (THE)",
  },
  KPW: {
    id: 408,
    code: "KPW",
    currency_name: "North Korean Won",
    region: "KOREA (THE DEMOCRATIC PEOPLE'S REPUBLIC OF)",
  },
  KRW: {
    id: 410,
    code: "KRW",
    currency_name: "South Korean Won",
    region: "KOREA (THE REPUBLIC OF)",
  },
  KWD: {
    id: 414,
    code: "KWD",
    currency_name: "Kuwaiti Dinar",
    region: "KUWAIT",
  },
  KYD: {
    id: 136,
    code: "KYD",
    currency_name: "Cayman Islands Dollar",
    region: "CAYMAN ISLANDS (THE)",
  },
  KZT: {
    id: 398,
    code: "KZT",
    currency_name: "Kazakhstani Tenge",
    region: "KAZAKHSTAN",
  },
  LAK: {
    id: 418,
    code: "LAK",
    currency_name: "Laotian Kip",
    region: "LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)",
  },
  LBP: {
    id: 422,
    code: "LBP",
    currency_name: "Lebanese Pound",
    region: "LEBANON",
  },
  LKR: {
    id: 144,
    code: "LKR",
    currency_name: "Sri Lanka Rupee",
    region: "SRI LANKA",
  },
  LRD: {
    id: 430,
    code: "LRD",
    currency_name: "Liberian Dollar",
    region: "LIBERIA",
  },
  LSL: {
    id: 426,
    code: "LSL",
    currency_name: "Lesotho Loti",
    region: "LESOTHO",
  },
  LYD: {
    id: 434,
    code: "LYD",
    currency_name: "Libyan Dinar",
    region: "LIBYA",
  },
  MAD: {
    id: 504,
    code: "MAD",
    currency_name: "Moroccan Dirham",
    region: "MOROCCO",
  },
  MDL: {
    id: 498,
    code: "MDL",
    currency_name: "Moldovan Leu",
    region: "MOLDOVA (THE REPUBLIC OF)",
  },
  MGA: {
    id: 969,
    code: "MGA",
    currency_name: "Malagasy Ariary",
    region: "MADAGASCAR",
  },
  MKD: {
    id: 807,
    code: "MKD",
    currency_name: "Macedonian Denar",
    region: "MACEDONIA",
  },
  MMK: {
    id: 104,
    code: "MMK",
    currency_name: "Myanma Kyat",
    region: "MYANMAR",
  },
  MNT: {
    id: 496,
    code: "MNT",
    currency_name: "Mongolian Tugrik",
    region: "MONGOLIA",
  },
  MOP: {
    id: 446,
    code: "MOP",
    currency_name: "Macanese Pataca",
    region: "MACAO",
  },
  MUR: {
    id: 480,
    code: "MUR",
    currency_name: "Mauritius Rupee",
    region: "MAURITIUS",
  },
  MVR: {
    id: 462,
    code: "MVR",
    currency_name: "Maldivian Rufiyaa",
    region: "MALDIVES",
  },
  MWK: {
    id: 454,
    code: "MWK",
    currency_name: "Malawian Kwacha",
    region: "MALAWI",
  },
  MXN: {
    id: 484,
    code: "MXN",
    currency_name: "Mexican Peso",
    region: "MEXICO",
  },
  MYR: {
    id: 458,
    code: "MYR",
    currency_name: "Malaysian Ringgit",
    region: "MALAYSIA",
  },
  MZN: {
    id: 943,
    code: "MZN",
    currency_name: "Mozambique Metical",
    region: "MOZAMBIQUE",
  },
  NAD: {
    id: 516,
    code: "NAD",
    currency_name: "Namibia Dollar",
    region: "NAMIBIA",
  },
  NGN: {
    id: 566,
    code: "NGN",
    currency_name: "Nigerian Naira",
    region: "NIGERIA",
  },
  NIO: {
    id: 558,
    code: "NIO",
    currency_name: "Cordoba Oro",
    region: "NICARAGUA",
  },
  NOK: {
    id: 578,
    code: "NOK",
    currency_name: "Norwegian Krone",
    region: "NORWAY",
  },
  NPR: {
    id: 524,
    code: "NPR",
    currency_name: "Nepalese Rupee",
    region: "NEPAL",
  },
  NZD: {
    id: 554,
    code: "NZD",
    currency_name: "New Zealand Dollar",
    region: "NEW ZEALAND",
  },
  OMR: {
    id: 512,
    code: "OMR",
    currency_name: "Rial Omani",
    region: "OMAN",
  },
  PAB: {
    id: 590,
    code: "PAB",
    currency_name: "Panamanian Balboa",
    region: "PANAMA",
  },
  PEN: {
    id: 604,
    code: "PEN",
    currency_name: "Peruvian Nuevo Sol",
    region: "PERU",
  },
  PGK: {
    id: 598,
    code: "PGK",
    currency_name: "Papua Kina",
    region: "PAPUA NEW GUINEA",
  },
  PHP: {
    id: 608,
    code: "PHP",
    currency_name: "Philippine Peso",
    region: "PHILIPPINES (THE)",
  },
  PKR: {
    id: 586,
    code: "PKR",
    currency_name: "Pakistan Rupee",
    region: "PAKISTAN",
  },
  PLN: {
    id: 985,
    code: "PLN",
    currency_name: "Polish Zloty",
    region: "POLAND",
  },
  PYG: {
    id: 600,
    code: "PYG",
    currency_name: "Paraguayan Guarani",
    region: "PARAGUAY",
  },
  QAR: {
    id: 634,
    code: "QAR",
    currency_name: "Qatari Rial",
    region: "QATAR",
  },
  RON: {
    id: 946,
    code: "RON",
    currency_name: "Romanian Leu",
    region: "ROMANIA",
  },
  RSD: {
    id: 941,
    code: "RSD",
    currency_name: "Serbian Dinar",
    region: "SERBIA",
  },
  RUB: {
    id: 643,
    code: "RUB",
    currency_name: "Russian Ruble",
    region: "RUSSIAN FEDERATION (THE)",
  },
  RWF: {
    id: 646,
    code: "RWF",
    currency_name: "Rwanda Franc",
    region: "RWANDA",
  },
  SAR: {
    id: 682,
    code: "SAR",
    currency_name: "Saudi Riyal",
    region: "SAUDI ARABIA",
  },
  SBD: {
    id: 090,
    code: "SBD",
    currency_name: "Solomon Islands Dollar",
    region: "SOLOMON ISLANDS",
  },
  SCR: {
    id: 690,
    code: "SCR",
    currency_name: "Seychelles Rupee",
    region: "SEYCHELLES",
  },
  SDG: {
    id: 938,
    code: "SDG",
    currency_name: "Sudanese Pound",
    region: "SUDAN (THE)",
  },
  SEK: {
    id: 752,
    code: "SEK",
    currency_name: "Swedish Krona",
    region: "SWEDEN",
  },
  SGD: {
    id: 702,
    code: "SGD",
    currency_name: "Singapore Dollar",
    region: "SINGAPORE",
  },
  SHP: {
    id: 654,
    code: "SHP",
    currency_name: "Saint Helena Pound",
    region: "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA",
  },
  SLL: {
    id: 694,
    code: "SLL",
    currency_name: "Leone",
    region: "SIERRA LEONE",
  },
  SOS: {
    id: 706,
    code: "SOS",
    currency_name: "Somali Shilling",
    region: "SOMALIA",
  },
  SRD: {
    id: 968,
    code: "SRD",
    currency_name: "Surinam Dollar",
    region: "SURINAME",
  },
  SVC: {
    id: 222,
    code: "SVC",
    currency_name: "El Salvador Colon",
    region: "EL SALVADOR",
  },
  SYP: {
    id: 760,
    code: "SYP",
    currency_name: "Syrian Pound",
    region: "SYRIAN ARAB REPUBLIC",
  },
  SZL: {
    id: 748,
    code: "SZL",
    currency_name: "Swazi Lilangeni",
    region: "SWAZILAND",
  },
  THB: {
    id: 764,
    code: "THB",
    currency_name: "Thai Baht",
    region: "THAILAND",
  },
  TJS: {
    id: 972,
    code: "TJS",
    currency_name: "Tajikistani Somoni",
    region: "TAJIKISTAN",
  },
  TMT: {
    id: 934,
    code: "TMT",
    currency_name: "Turkmenistan New Manat",
    region: "TURKMENISTAN",
  },
  TND: {
    id: 788,
    code: "TND",
    currency_name: "Tunisian Dinar",
    region: "TUNISIA",
  },
  TOP: {
    id: 776,
    code: "TOP",
    currency_name: "Tongan Paʻanga",
    region: "TONGA",
  },
  TRY: {
    id: 949,
    code: "TRY",
    currency_name: "Turkish Lira",
    region: "TURKEY",
  },
  TTD: {
    id: 780,
    code: "TTD",
    currency_name: "Trinidad and Tobago Dollar",
    region: "TRINIDAD AND TOBAGO",
  },
  TWD: {
    id: 901,
    code: "TWD",
    currency_name: "New Taiwan Dollar",
    region: "TAIWAN (PROVINCE OF CHINA)",
  },
  TZS: {
    id: 834,
    code: "TZS",
    currency_name: "Tanzanian Shilling",
    region: "TANZANIA, UNITED REPUBLIC OF",
  },
  UAH: {
    id: 980,
    code: "UAH",
    currency_name: "Ukrainian Hryvnia",
    region: "UKRAINE",
  },
  UGX: {
    id: 800,
    code: "UGX",
    currency_name: "Uganda Shilling",
    region: "UGANDA",
  },
  USD: {
    id: 840,
    code: "USD",
    currency_name: "US Dollar",
    region: "UNITED STATES OF AMERICA",
  },
  UYU: {
    id: 858,
    code: "UYU",
    currency_name: "Peso Uruguayo",
    region: "URUGUAY",
  },
  UZS: {
    id: 860,
    code: "UZS",
    currency_name: "Uzbekistan Sum",
    region: "UZBEKISTAN",
  },
  VEF: {
    id: 937,
    code: "VEF",
    currency_name: "Venezuelan Bolivar",
    region: "VENEZUELA (BOLIVARIAN REPUBLIC OF)",
  },
  VND: {
    id: 704,
    code: "VND",
    currency_name: "Vietnamese Dong",
    region: "VIET NAM",
  },
  VUV: {
    id: 548,
    code: "VUV",
    currency_name: "Vanuatu Vatu",
    region: "VANUATU",
  },
  WST: {
    id: 882,
    code: "WST",
    currency_name: "Samoan Tala",
    region: "SAMOA",
  },
  XAF: {
    id: 950,
    code: "XAF",
    currency_name: "CFA Franc BEAC",
    region: "CENTRAL AFRICAN",
  },
  XCD: {
    id: 951,
    code: "XCD",
    currency_name: "East Caribbean Dollar",
    region: "EASTERN CARIBBEAN STATES",
  },
  XDR: {
    id: 960,
    code: "XDR",
    currency_name: "SDR (Special Drawing Right)",
    region: "INTERNATIONAL MONETARY FUND (IMF)",
  },
  XOF: {
    id: 952,
    code: "XOF",
    currency_name: "CFA Franc BCEAO",
    region: "WEST AFRICAN",
  },
  XPF: {
    id: 953,
    code: "XPF",
    currency_name: "CFP Franc",
    region: "FRENCH COLONIES OF THE PACIFIC",
  },
  YER: {
    id: 886,
    code: "YER",
    currency_name: "Yemeni Rial",
    region: "YEMEN",
  },
  ZAR: {
    id: 710,
    code: "ZAR",
    currency_name: "South African Rand",
    region: "SOUTH AFRICA",
  },
  ZMW: {
    id: 967,
    code: "ZMW",
    currency_name: "Zambian Kwacha",
    region: "ZAMBIA",
  },
  ZWL: {
    id: 932,
    code: "ZWL",
    currency_name: "Zimbabwe Dollar",
    region: "ZIMBABWE",
  },
});
