module.exports = Object.freeze({
  // APIs URL
  STEAM_API_URL: "http://store.steampowered.com/api",
  CURRENCY_API_URL: "https://api.apilayer.com/exchangerates_data",

  // CURRENCIES
  EURO: "EUR",
  US_DOLLARS: "USD",
  TURKISH_LIRA: "TL",
  ARGENTINE_PESOS: "ARS",

  // ENVIRONMENTS
  LOCAL_ENV: "LOCAL",
  RENDER_ENV: "RENDER",

  // TABLES TYPES
  SELECT_ALL: "SELECT_ALL",
  DROP_TABLE: "DROP_TABLE",
  SELECT_FROM: "SELECT_FROM",
  CREATE_TABLE: "CREATE_TABLE",
  INSERT_TABLE: "INSERT_TABLE",
  SELECT_EXISTS: "SELECT_EXISTS",
  SELECT_LASTEST_CUR_VAL: "SELECT_LASTEST_CUR_VAL",

  // TABLES
  CURRENCIES: "CURRENCIES",
  GAMES: "GAMES",
});
